### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by LynBean**
### This pull request...
  - [ ] Fixes a bug
  - [x] Introduces a new feature
  - [x] Improves an existing feature
  - [ ] Boosts code quality or performance

### Description
- `play` command will let the bot join voice channel and play the default playlist if there's no song being selected and default playlist has been configured

- Docker image
  - The bot has been configured to fetch the token and owner id from the environment variables during first run if it is running inside a docker container
  - Pull from `alpine`
  - `bash`, `nano`, `openjdk-17` has been configured to be installed in the image
  - Final Image size will be around 300mb

### CODE REVIEW

**Comment by LynBean** [comment]
I tried the way from https://github.com/lightbend/config#optional-system-or-env-variable-overrides

By setting the JVM property `-Dconfig.override_with_env_vars=true`,
And the environment variables, `CONFIG_FORCE_token` and `CONFIG_FORCE_owner`, with values set,

The bot will still try to prompt user for the token during first run.

**Comment by MrMightyNighty** [comment]
Any update when this is going to be merged?

**Comment by LynBean** [comment]
> There's no need to make code modifications to use environment variables in the config; HOCON natively supports env vars

Now it overrides the value from the `CONFIG_FORCE_token` and `CONFIG_FORCE_owner` env vars

And I also made the Github workflow for Docker image CI

**Comment by LynBean** [comment]
> [!IMPORTANT]
> This feature is still maintaining under [feature/docker](https://github.com/LynBean/Jagrosh-MusicBot/tree/feature/docker)

**Pull request closed without merging**
