### PR TITLE
Create "Signing into YouTube" wiki page

### PR DESCRIPTION
**Pull request by MichailiK**
Depends on #1670 

Adds documentation regarding signing into YouTube to the JMusicBot wiki.

### CODE REVIEW

**Comment by MichailiK** [comment]
Here's a render of that page as of commit [`e843516`](https://github.com/jagrosh/MusicBot/pull/1714/commits/e8435168394d4447d812fb2da1972052a9970dcd):



(open in browser to zoom in)

**Review by MichailiK — COMMENTED** [review]
This could use a FAQ section regarding risks and such for signing in

**Comment by NatanMB22** [comment]
The bot won't DM my account
I've already tried different versions, putting it to =false and then =true and vice-versa
And also nothing on the .jar console

**Comment by MichailiK** [comment]
I'm uncomfortable merging this at the moment, as several new issues have been emerging, making sign in via OAuth2 ineffective.

**Comment by MichailiK** [comment]
Google probably has rolled out a fix for this workaround to everyone by now.

**Pull request closed without merging**
