### PR TITLE
Support new Discord username

### PR DESCRIPTION
**Pull request by MagicTeaMC**
### This pull request...
  - [x] Fixes a bug
  - [ ] Introduces a new feature
  - [ ] Improves an existing feature
  - [ ] Boosts code quality or performance

### Description
A easy way to support Discord new username(maybe

### Purpose
圖片
圖片

### CODE REVIEW

**Comment by jagrosh** [comment]
I don't like how this is implemented; I think we should add a formatting function somewhere that will handle the logic, and then use the formatted output anywhere we need the username

**Comment by MagicTeaMC** [comment]
discord will force all user to use new username, so we don't need to check username anymore :)

**Comment by jagrosh** [comment]
Either way I think it would still be good to make a specific formatting function for usernames. Discrims will still exist for a bit longer (this would be a future-proof solution) and then it becomes easier to make other formatting changes in the future (for example, showing display name instead of username, or showing a combination of them).

**Review by MichailiK — CHANGES_REQUESTED** [review]
The new `formatUsername` utility is missing usage in 2 places:

https://github.com/jagrosh/MusicBot/blob/8457f944cdaada4f37f0c305624d0b292a2b6043/src/main/java/com/jagrosh/jmusicbot/commands/dj/ForceskipCmd.java#L45

https://github.com/jagrosh/MusicBot/blob/8457f944cdaada4f37f0c305624d0b292a2b6043/src/main/java/com/jagrosh/jmusicbot/commands/music/SkipCmd.java#L69

**Review by MichailiK — APPROVED** [review]

**Pull request merged**
