### PR TITLE
Update lavaplayer youtube source to 1.5.2

### LINKED ISSUE #1651: Bot doesn't play music at all
### Bug Description

It started on 7nd August

### Steps to Reproduce

Launch the bot.
Play something from YouTube.
Bot just joins the channel and nothing.

### Expected Result

Bot should play music.

### Debug Output

[00:22:03] [ERROR] [SignatureCipherManager]: Problematic YouTube player script /s/player/b12cc44b/player_ias.vflset/ru_RU/base.js detected (issue detected with script: no n function match). Dumped to C:\Users\shoke\AppData\Local\Temp\lavaplayer-yt-player-script12383617030419906327.js
[00:24:38] [ERROR] [LocalAudioTrackExecutor]: Error in playback of TVW2KZlxvWI
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
    at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45)
    at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121)
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Not success status code: 403
    at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88)
    at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124)
    at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106)
    at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158)
    at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174)
    at java.base/java.io.DataInputStream.readUnsignedByte(Unknown Source)
    at java.base/java.io.DataInputStream.readByte(Unknown Source)
    at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
    at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:47)
    at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:94)
    at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52)
    at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35)
    at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
    at dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:148)
    at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:116)
    at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
    at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)

### Additional Info

_No response_

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.3

### PR DESCRIPTION
**Pull request by MichailiK**
### This pull request...
  - [x] Fixes a bug
  - [ ] Introduces a new feature
  - [ ] Improves an existing feature
  - [ ] Boosts code quality or performance

### Description
Updates the youtube source to the latest 1.5.2 version

### Purpose
Fixes 403 issues people are encountering as YouTube has changed the cipher script... again.

### Relevant Issue(s)
Fixes #1651

### CODE REVIEW

**Review by LastRoze — APPROVED** [review]

**Comment by Bandanakeks** [comment]
Is there a way to get the build of this without waiting for merge?

**Comment by Griinjah** [comment]
> Is there a way to get the build of this without waiting for merge?

wish i knew how to compile this to fix it LMAO

**Comment by 10Maximus10** [comment]
> Is there a way to get the build of this without waiting for merge?
Compile it yourself
Install maven then use this command to compile it "mvn --batch-mode --update-snapshots verify"

**Comment by versionDefect** [comment]
that worked. thanks!

**Comment by Err2101** [comment]
do you have any more info on how to compile from source? I downloaded the repository and updated pom.xml but not sure how to compile it to a jar file.

**Comment by versionDefect** [comment]
> do you have any more info on how to compile from source? I downloaded the repository and updated pom.xml but not sure how to compile it to a jar file.

basically what the previous person said, install maven on to your system, i used apt get on my ubuntu VM. Clone the repo, and run the command. don't over think it

**Comment by Err2101** [comment]
Thanks this worked! for any newbies like me, after you clone the repository and the maven command, you will use the /target/JMusicBot-Snapshot-All.jar file to run JMusicBot.

**Comment by twl-surrogate** [comment]
> > Is there a way to get the build of this without waiting for merge?
> 
> Compile it yourself Install maven then use this command to compile it "mvn --batch-mode --update-snapshots verify"

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.709 s
[INFO] Finished at: 2024-08-12T12:20:35-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project JMusicBot: Could not resolve dependencies for project com.jagrosh:JMusicBot:jar:Snapshot: Failed to collect dependencies at com.jagrosh:jda-utilities:pom:3.0.5 -> com.jagrosh:jda-utilities-command:jar:3.0.5: Failed to read artifact descriptor for com.jagrosh:jda-utilities-command:jar:3.0.5: Could not transfer artifact com.jagrosh:jda-utilities-command:pom:3.0.5 from/to central (https://jcenter.bintray.com): Transfer failed for https://jcenter.bintray.com/com/jagrosh/jda-utilities-command/3.0.5/jda-utilities-command-3.0.5.pom 502 Bad Gateway -> [Help 1]
```

**Pull request merged**
