### PR TITLE
Update dependencies to fix youtube issues

### LINKED ISSUE #1595: [Bug Report] Playing video from youtube doesnt work
### Bug Description

When playing a youtube video
the bot doesnt play the audio and i get this traceback:
````
Jun 23 19:47:33 pi64-1 env[1297069]: [19:47:33] [ERROR] [LocalAudioTrackExecutor]: Error in playback of EpcDH9faOQw
Jun 23 19:47:33 pi64-1 env[1297069]: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
Jun 23 19:47:33 pi64-1 env[1297069]:         at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
Jun 23 19:47:33 pi64-1 env[1297069]:         at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116)
Jun 23 19:47:33 pi64-1 env[1297069]:         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
Jun 23 19:47:33 pi64-1 env[1297069]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Jun 23 19:47:33 pi64-1 env[1297069]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Jun 23 19:47:33 pi64-1 env[1297069]:         at java.base/java.lang.Thread.run(Thread.java:829)
Jun 23 19:47:33 pi64-1 env[1297069]:         Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
Jun 23 19:47:33 pi64-1 env[1297069]:   lavaplayer.version: 1.3.78
Jun 23 19:47:33 pi64-1 env[1297069]:   os.arch: aarch64
Jun 23 19:47:33 pi64-1 env[1297069]:   os.name: Linux
Jun 23 19:47:33 pi64-1 env[1297069]:   os.version: 6.1.21-v8+
Jun 23 19:47:33 pi64-1 env[1297069]:   java.vendor: Debian
Jun 23 19:47:33 pi64-1 env[1297069]:   java.version: 11.0.23
Jun 23 19:47:33 pi64-1 env[1297069]:   java.runtime.version: 11.0.23+9-post-Debian-1deb11u1
Jun 23 19:47:33 pi64-1 env[1297069]:   java.vm.version: 11.0.23+9-post-Debian-1deb11u1
Jun 23 19:47:33 pi64-1 env[1297069]: Caused by: java.lang.RuntimeException: Not success status code: 403
Jun 23 19:47:33 pi64-1 env[1297069]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:87)
Jun 23 19:47:33 pi64-1 env[1297069]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:116)
Jun 23 19:47:33 pi64-1 env[1297069]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:105)
Jun 23 19:47:33 pi64-1 env[1297069]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:150)
Jun 23 19:47:33 pi64-1 env[1297069]:         at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:166)
Jun 23 19:47:33 pi64-1 env[1297069]:         at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270)
Jun 23 19:47:33 pi64-1 env[1297069]:         at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
Jun 23 19:47:33 pi64-1 env[1297069]:         at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:45)
Jun 23 19:47:33 pi64-1 env[1297069]:         at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:78)
Jun 23 19:47:33 pi64-1 env[1297069]:         at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:51)
Jun 23 19:47:33 pi64-1 env[1297069]:         at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:34)
Jun 23 19:47:33 pi64-1 env[1297069]:         at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
Jun 23 19:47:33 pi64-1 env[1297069]:         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57)
Jun 23 19:47:33 pi64-1 env[1297069]:         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49)
Jun 23 19:47:33 pi64-1 env[1297069]:         at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
Jun 23 19:47:33 pi64-1 env[1297069]:         ... 4 common frames omitted
````

### Steps to Reproduce

1. Start bot
2. Play any youtube video

### Expected Result

Audio to play / no traceback

### Debug Output

openjdk 11.0.23 2024-04-16
OpenJDK Runtime Environment (build 11.0.23+9-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.23+9-post-Debian-1deb11u1, mixed mode)

JMusicBot-0.4.1.jar

       _,met$$$$$gg.                                                                                                                                                                   g
    ,g$$$$$$$$$$$$$$$P.       ----------
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 11 (bullseye) aarch64
 ,$$P'              `$$$.     Host: Raspberry Pi 400 Rev 1.1
',$$P       ,ggs.     `$$b:   Kernel: 6.1.21-v8+
`d$$'     ,$P"'   .    $$$    Uptime: 23 days, 3 hours, 40 mins
 $$P      d$'     ,    $$P    Packages: 1531 (dpkg)
 $$:      $$.   -    ,d$$'    Shell: bash 5.1.4
 $$;      Y$b._   _,d$P'      Terminal: /dev/pts/0
 Y$$.    `.`"Y$$$$P"'         CPU: BCM2835 (4) @ 1.800GHz
 `$$b      "-.__              Memory: 766MiB / 3794MiB
  `Y$$
   `Y$$.
     `$$b.
       `Y$$b.
          `"Y$b._
              `"""

### Additional Info

_No response_

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: Release

### LINKED ISSUE #1608: [Bug Report] bot joins to rooms and leave
### Bug Description

The bot joins the voice channel, after which it turns off, without playing the video. A few days ago, everything worked great

log
[13:18:30] [INFO] [JMusicBot]: Loaded config from C:\Users\Administrator\Desktop\popa\config.txt
[13:18:31] [INFO] [JDA]: Login Successful!
[13:18:31] [INFO] [JMusicBot]: JMusicBot
[13:18:31] [INFO] [WebSocketClient]: Connected to WebSocket
[13:18:32] [INFO] [JDA]: Finished Loading!
[13:18:37] [ERROR] [SignatureCipherManager]: Problematic YouTube player script /s/player/9ed4a7e1/player_ias.vflset/en_GB/base.js detected (issue detected with script: no n function match). Dumped to C:\Users\ADMINI~1\AppData\Local\Temp\2\lavaplayer-yt-player-script8122431706077840409.js
[13:18:37] [ERROR] [LocalAudioTrackExecutor]: Error in playback of iM0wijccu_I
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:330)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.RuntimeException: Not success status code: 403
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174)
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:271)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:74)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35)
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:140)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:108)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:63)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101)
	... 4 common frames omitted
[13:18:37] [ERROR] [AudioHandler]: Track iM0wijccu_I has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:330)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.RuntimeException: Not success status code: 403
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174)
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:271)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:74)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35)
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:140)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:108)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:63)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101)
	... 4 common frames omitted

image

### Steps to Reproduce

1. enable bot
2. use play
3. bot join to room
4. bot leave

### Expected Result

idk

### Debug Output

idk

### Additional Info

_No response_

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: Release

### LINKED ISSUE #1610: Bot joins then leaves VC immediately (Youtube links specifically)
### Bug Description

I saw the dependencies were just updated, and now the bot immediately leaves when called to a vc for a youtube link. It responds to the command, joins for half a second, then leaves without playing the requested video/audio.

[18:24:11] [INFO] [JMusicBot]: Loaded config from C:\Users\Bianca\Documents\VoidBot\config.txt
[18:24:11] [INFO] [JDA]: Login Successful!
[18:24:12] [INFO] [JMusicBot]: JMusicBot
[18:24:12] [INFO] [WebSocketClient]: Connected to WebSocket
[18:24:12] [INFO] [JDA]: Finished Loading!
[18:24:20] [ERROR] [SignatureCipherManager]: Problematic YouTube player script /s/player/b22ef6e7/player_ias.vflset/en_US/base.js detected (issue detected with script: no n function match). Dumped to C:\Users\Bianca\AppData\Local\Temp\lavaplayer-yt-player-script2368314145694134733.js
[18:24:21] [ERROR] [LocalAudioTrackExecutor]: Error in playback of hS5SGXJfL2E
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:330)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Not success status code: 403
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174)
	at java.base/java.io.DataInputStream.readByte(Unknown Source)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:74)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35)
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:140)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:108)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:63)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101)
	... 4 common frames omitted
[18:24:21] [ERROR] [AudioHandler]: Track hS5SGXJfL2E has failed to play
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:330)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Not success status code: 403
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174)
	at java.base/java.io.DataInputStream.readByte(Unknown Source)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:74)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35)
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:140)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:108)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:63)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101)
	... 4 common frames omitted

### Steps to Reproduce

1. enable the bot
2. use the play function using a youtube link
3. Bot should join then immediately leave the vc room

### Expected Result

I expected the bot to play the video audio, but it didn't it immediately left upon joining

### Debug Output

bruh

### Additional Info

I saw that the  dependencies were updated 25 minutes ago to resolve a similar problem, but it didnt actually solve it.

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: Release

### PR DESCRIPTION
**Pull request by Morilli**
### This pull request...
  - [x] Fixes a bug

### Description
Updates the lavaplayer and youtube-source dependencies to their latest versions.

### Purpose
This fixes recent play issues with youtube videos.

### Relevant Issue(s)
- closes #1608
- closes #1595
- closes #1610
- *might* (fix) #1588

### CODE REVIEW

**Review by John-Ingram — APPROVED** [review]

**Comment by VanillaChan6571** [comment]
Those of who are building from source:

Add the following to the bottom of the config.txt:

lyrics.user-agent=JMusicBot
lyrics.timeout=600 *(Or whatever number you wish)

**Comment by TheBlueking** [comment]
i just downloaded the .jar file for this how would i implement this change i'm sorry i'm new to this

**Comment by esc-0-bar** [comment]
Is it working with this fix?

**Comment by ahanwek** [comment]
how to implement this on .jar  i dont know, im new to this

**Comment by ErdbeerbaerLP** [comment]
It does work. Tested on my [fork](https://github.com/ErdbeerbaerLP/musicbot)

**Review by MichailiK — APPROVED** [review]

**Comment by Gobidev** [comment]
This didn't fix the issue for me, I've also heard about NewPipe and yt-dlp having playback issues, see https://github.com/TeamNewPipe/NewPipe/issues/11255

**Comment by MichailiK** [comment]
From what I've gathered, the recent 403 issues may be caused by:

1. IP ban ("Sign in to confirm you're not a bot.") There's currently no ideal workaround for that.
2. Failing the cipher check that YouTube recently updated. The lavalink devs have fixed this in lavaplayer 1.4.0 & this PR updates lavaplayer.
3. Having an outdated visitor info/data cookie (which lavaplayer already updates frequently)

The first issue is tracked in #1588, the second issue is fixed in JMusicBot 0.4.2, and the third one is not applicable. If you still encounter 403 issues with 0.4.2, consider opening an issue.

**Comment by brlan10** [comment]
> From what I've gathered, the recent 403 issues may be caused by:
> 
> 1. IP ban ("Sign in to confirm you're not a bot.") There's currently no ideal workaround for that.
> 2. Failing the cipher check that YouTube recently updated. The lavalink devs have fixed this in the youtube source 1.4.0 & this PR updates the source.
> 3. Having an outdated visitor info/data cookie (which lavaplayer/the youtube source already update frequently)
> 
> The first issue is tracked in #1588, the second issue is fixed in JMusicBot 0.4.2, and the third one shouldn't be applicable for JMusicBot/lavaplayer. If you still encounter 403 issues with 0.4.2, consider opening an issue.

1. not getting this one.  I was able to reproduce with a vpn, but on my default IP, I do not get this error
2. I am using 0.4.2 and still unable to play videos, experiencing error 403 where bot joins, then leaves instantly.
3. well, if this is not applicable either, I guess I'll open a new issue.

**Comment by MichailiK** [comment]
@brlan10 keep in mind you're commenting under a 3 week old PR. As of 2 days ago, YouTube updated their cipher check again, thus requiring another update for the youtube source & thus a JMusicBot 0.4.3 release.

**Pull request merged**
