### PR TITLE
Fix Twitch integration

### PR DESCRIPTION
**Pull request by drozycki**
### This pull request...
  - [x] Fixes a bug
  - [ ] Introduces a new feature
  - [ ] Improves an existing feature
  - [ ] Boosts code quality or performance

### Description
The Lavaplayer Twitch bug has been recently fixed https://github.com/sedmelluq/lavaplayer/issues/473

This is the PR that fixed the bug https://github.com/sedmelluq/lavaplayer/pull/480

This change updates lavaplayer to 1.3.49, which has the bug fix included.

### CODE REVIEW

**Comment by Sanduhr32** [comment]
The you also should check that it fixes a bug :eyes:

**Comment by drozycki** [comment]
@Sanduhr32 It should work in theory but nothing's fixed till it's tested 😉

I haven't found any documentation of the build process. How do I build the jar from source? I get this error when running `maven` on the provided `pom.xml`:

```
$ mvn
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.260 s
[INFO] Finished at: 2020-05-22T07:36:56-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException
```

**Comment by Sanduhr32** [comment]
Githubs CI builds all finished successfully. I would say that that is enough.

**Comment by drozycki** [comment]
@Sanduhr32 @jagrosh Could someone merge this in?

**Comment by jagrosh** [comment]
I'm pretty sure this will be superseded by my fixes to youtube loading and discord ratelimits

**Comment by jagrosh** [comment]
This has been superseded by https://github.com/jagrosh/MusicBot/commit/c5a583b96f9ab84450c460a427114e1f45f08af6

**Pull request closed without merging**
