### PR TITLE
Fix bot staying in channel when loading track fails

### LINKED ISSUE #129: Bot stays in channel after adding invalid link to queue.
I am running the latest version (0.1.2) on Ubuntu Server 16.04. When anyone adds a link from youtube that is "unavailable" when you open it in your browser then bot stays in voice channel even though stayinchannel is set to false in config. There are no errors in console output.

### PR DESCRIPTION
**Pull request by MichailiK**
### This pull request...
  - [x] Fixes a bug
  - [ ] Introduces a new feature
  - [ ] Improves an existing feature
  - [ ] Boosts code quality or performance

### Description
This PR fixes #129, where the bot stays in the voice channel when loading a track fails (i.e. the track hasn't been found).
I can imagine that many people dislike my fix, especially because it looks hacky.

### Purpose
See description

### Relevant Issue(s)
This PR closes #129

### CODE REVIEW

**Comment by MichailiK** [comment]
Oh. I thought putting each feature / bug fix in it's individual PR is good practice so maintainers can easily merge or close them individually.

**Comment by Sanduhr32** [comment]
Since all of your prs are about bug fixes, improve an existing feature / enhance the code quality of the same files it wouldn't have mattered. Btw I hope you get those 3 merged for your hacktoberfest

**Comment by MichailiK** [comment]
Oh, I didn't even knew the Hacktoberfest even existed, thank you for the tip :P

**Comment by jagrosh** [comment]
All JMusicBot versions are manually released, so separate PRs doesn't cause any issues. As mentioned, it also makes it easier to filter through which things can be merged right away vs what needs changes.

**Comment by jagrosh** [comment]
The reasons I haven't merged this yet:
- I haven't tested this yet
- I'm a bit concerned about the potential for a race-condition with loading multiple things or when loading things immediately after using other commands
- This same issue would be effectively resolved by adding an additional feature: a setting for what to do when nobody is in the voice channel (not _quite_ the same solution, but fixes the same overall problem of the bot being left in the channel doing nothing)

**Comment by MichailiK** [comment]
This PR is superseded by #583.

**Pull request closed without merging**
