### PR TITLE
Add custom command to launch frequently used URL

### PR DESCRIPTION
**Pull request by Wobak**
### This pull request...
  - [ x ] Introduces a new feature

### Description
This commands implements the <prefix>custom command which allows to use the shortcuts config to run commands such as 
!custom mymusic to avoid using the full URL every time.

### Purpose
When using the same music multiple times, it might be useful to add it in the config for custom calls

### Relevant Issue(s)
None noted

### CODE REVIEW

**Comment by MichailiK** [comment]
You seem to have changed every file's mode/permission in the project, thus creating a diff out of every file. You also unintentionally committed [binaries](https://github.com/jagrosh/MusicBot/tree/e2303ecfacfd541b781d8755fbdceeb12bd8648c/src/main/resources/natives) and other unwanted files into your branch. Please undo those, then force-push your changes into the branch.

**Comment by Wobak** [comment]
Hello,

OK let me try to review that.

However the binaries are now in the main project as part of last commit : https://github.com/jagrosh/MusicBot/tree/master/src/main/resources/natives

**Comment by MichailiK** [comment]
Oh. I apologize, I never noticed they were added. I got confused, since every file is being shown as modified in this PR. It'd be great if all the files can be reset back to how they are in our master branch.

**Comment by Wobak** [comment]
We added 2 commits with the reset of permissions and the new code logic. Let me know if this is good or not :)

**Comment by Wobak** [comment]
I'm changing a few steps for the integration to be more consistent with the rest of the project.

**Comment by Wobak** [comment]
@jagrosh, any chance this can make it to the repo? I don't mind if you don't want to, just refuse the PR so that I know :)

Thanks again for the hard work !

**Comment by Wobak** [comment]
This is now broken following the update on Lavacommand & so on.

**Pull request closed without merging**
