### PR TITLE
Delete LICENSE

### PR DESCRIPTION
**Pull request by AHIRAISSHY**

### CODE REVIEW

**Comment by AngerKingz** [comment]
It was for my version of this git project

**Comment by jagrosh** [comment]
Please do not remove the license, as removing it violates the license itself.

**Comment by samjmckenzie** [comment]
Can I just say this is hilarious lol

**Comment by AngerKingz** [comment]
Go ahead XD

**Comment by wickedlizerd** [comment]
Commit of the century.

**Comment by AngerKingz** [comment]
i am fucking meme god damn it XD

**Pull request closed without merging**
