### PR TITLE
Fix warnings and deprecations

### PR DESCRIPTION
**Pull request by t3rminus**
### This pull request...
  - [ ] Fixes a bug
  - [ ] Introduces a new feature
  - [ ] Improves an existing feature
  - [X] Boosts code quality or performance

### Description
Fixes a bunch of warnings and deprecations

### Purpose
Keep things nice and clean :)

### CODE REVIEW

**Comment by MichailiK** [comment]
I'm sorry for the lack of response. The reason we haven't really responded to this PR, is because we've been planning on doing our  own major refactor when adding slash commands & localization to JMusicBot.

**Comment by bigkitttty** [comment]
hows major refactor coming along

**Comment by MichailiK** [comment]
We are first adding slash commands & l10n to JDA-Utilities, before we start work on JMusicBot.

**Comment by bigkitttty** [comment]
Thank you, but what's JDA-Utilities?

**Comment by MichailiK** [comment]
JDA-Utilities is a library which manages all of JMusicBot's commands. Once we add slash commands to JDA-Utilities, we can update JMusicBot to use slash commands, and clean up the code along the way.

**Comment by bigkitttty** [comment]
Why is  JDA-Utilities in Java not js

**Comment by bigkitttty** [comment]
A note js is for JavaScript

**Comment by MichailiK** [comment]
We use Java, as lavaplayer, a popular library for playing music on Discord, is also written in Java. Please stop commenting about this here.

**Pull request merged**
