### PR TITLE
Dockerfile, gitignore, dockerignore, and example config.txt for easy setup on any server.

### PR DESCRIPTION
**Pull request by bekilo**

### CODE REVIEW

**Comment by aliasfalse** [comment]
so much like. @jagrosh plez

**Comment by aliasfalse** [comment]
@bekilo maybe rebase?

**Comment by bekilo** [comment]
@aliasfalse  would love to but it seems commit 0f52bbd1701ce95699f575294a659143de8865ce broke maven, then 9be9a488824cdc38cf0f88b97a18484fab783f9d removed pom.xml entirely so i don't know what @jagrosh is doing right now.

**Comment by aliasfalse** [comment]
oh, well that's not cool

**Comment by SplitPixl** [comment]
A thought, what if configuration could be set with environment variables? Would make it easier for deploying it just running a command like:

`docker run -e "BOT_TOKEN=iamatoken" -e "BOT_PREFIX=mm!" -e "BOT_OWNER=someid" -d jmusicbot:latest`

Also looking at the state of the conflicting files dialogue, it seems like something has gone very wrong with this branch.

**Comment by jagrosh** [comment]
The new configuration library might actually support environment variables natively (I haven't checked), but regardless, for this to be added the branch will need to be brought up-to-date (ideally a fresh branch off master).

**Comment by jagrosh** [comment]
I would still like to see docker support added, but I'm closing this PR as this particular branch has many conflicts and hasn't been touched in months.

**Pull request closed without merging**
