### PR TITLE
Add Oracle Cloud to Hosting documentation

### PR DESCRIPTION
**Pull request by SplitPixl**
### This pull request...
  - [ ] Fixes a bug
  - [ ] Introduces a new feature
  - [ ] Improves an existing feature
  - [ ] Boosts code quality or performance
  - [X] Improves Documentation

### Description
Add oracle cloud to hosting options

### Purpose
Tell people about more free hosting options

### Relevant Issue(s)
N/A

### CODE REVIEW

**Review by MichailiK — CHANGES_REQUESTED** [review]
There have been reports of Oracle seemingly hibernating/suspending instances that are idling. This should probably be mentioned. See #823

**Review by MichailiK — APPROVED** [review]

**Review by ELSMKSASOFFICAL — APPROVED** [review]

**Comment by SeaSon2002** [comment]
my account got suspended after 2 weeks without reason ( i contacted support but they werent helpful at all)

**Comment by YJSoft** [comment]
image

Since my account was suspended without warning(see above picture) and there are other reports too([Korean community article](https://xetown.com/topics/1600862)), I think that should be considered too.

**Review by MichailiK — CHANGES_REQUESTED** [review]
We have just switched to using MKDocs, which causes conflicts. I will deal with these now. Due to the above reports of users getting disabled, I would advise against merging this though.

**Pull request closed without merging**
